export const imagePath = {
  ace: require('../assets/building/ace.png'),
  centralLibrary: require('../assets/building/centralLibrary.png'),
  cheomdan: require('../assets/building/cheomdan.png'),
  economy: require('../assets/building/economy.png'),
  engineering: require('../assets/building/engineering.png'),
  engineering1: require('../assets/building/engineering1.png'),
  engineering2: require('../assets/building/engineering2.png'),
  engineering3: require('../assets/building/engineering3.png'),
  engineering4: require('../assets/building/engineering4.png'),
  fineArts: require('../assets/building/fineArts.png'),
  healthScience: require('../assets/building/healthScience.png'),
  ict: require('../assets/building/ict.png'),
  international: require('../assets/building/international.png'),
  legal: require('../assets/building/legal.png'),
  libralArts: require('../assets/building/libralArts.png'),
  main: require('../assets/building/main.png'),
  mirae: require('../assets/building/mirae.png'),
  modeling: require('../assets/building/modeling.png'),
  music: require('../assets/building/music.png'),
  pe: require('../assets/building/pe.png'),
  performingArts: require('../assets/building/performingArts.png'),
  rotc: require('../assets/building/rotc.png'),
  student: require('../assets/building/student.png'),
  dormitory: require('../assets/building/dormitory.png'),
  belkanto: require('../assets/building/belkanto.png'),
};
